# Back propogation using torch

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
import torch

**y=x^2**

In [3]:
x=torch.tensor(4.0,requires_grad=True)   #To execute back propogation too

In [4]:
x

tensor(4., requires_grad=True)

In [5]:
y=x**2

In [8]:
y

tensor(16., grad_fn=<PowBackward0>)

# Backpropogation 2x

In [6]:
y.backward()

In [9]:
x.grad

tensor(8.)

**After back propogation, it becomes 2x=> 2x4=8**

# Complex tensor

In [10]:
lst=[[2.,3.,1.],[4.,5.,3.],[7.,6.,4.]]

torch_input=torch.tensor(lst,requires_grad=True)

In [11]:
torch_input

tensor([[2., 3., 1.],
        [4., 5., 3.],
        [7., 6., 4.]], requires_grad=True)

**y=x^3+x^2**

In [12]:
y=torch_input**3 + torch_input**2

In [13]:
y

tensor([[ 12.,  36.,   2.],
        [ 80., 150.,  36.],
        [392., 252.,  80.]], grad_fn=<AddBackward0>)

In [14]:
z=y.sum()

In [15]:
z

tensor(1040., grad_fn=<SumBackward0>)

In [16]:
z.backward()

**3x^2+2x**

In [18]:
torch_input.grad

tensor([[ 16.,  33.,   5.],
        [ 56.,  85.,  33.],
        [161., 120.,  56.]])

In [20]:
y.backward()

RuntimeError: grad can be implicitly created only for scalar outputs