# Tensors in torch

**Tensors are replace numpy to use the power of gpu**

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
import torch

In [3]:
torch.__version__

'1.6.0'

In [4]:
list=[3,4,5,6]

In [5]:
arr=np.array(list)

In [7]:
type(arr)

numpy.ndarray

# Numpy to pytorch tensors

In [8]:
tensors=torch.from_numpy(arr)

tensors

tensor([3, 4, 5, 6])

In [10]:
tensors.dtype

torch.int64

In [9]:
type(tensors)

torch.Tensor

In [11]:
tensors[:3]

tensor([3, 4, 5])

In [13]:
tensors[:-1]

tensor([3, 4, 5])

In [14]:
tensors[3]=10

In [15]:
tensors

tensor([ 3,  4,  5, 10])

In [16]:
arr

array([ 3,  4,  5, 10])

**We can see the changes made in tensors is reflected to np array too as they refer to the same memory location**

**In order to avoid this,we can use tensor method instead of from_numpy**

# Using torch.tensor

In [17]:
ten_arr=torch.tensor(arr)

**It creates a another copy of arr to ten_arr**

In [18]:
ten_arr[3]=50

print(ten_arr)

print(arr)

tensor([ 3,  4,  5, 50])
[ 3  4  5 10]


In [20]:
torch.zeros(2,3,dtype=torch.float32)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

# Arithmetic operation

In [21]:
a=torch.tensor([1,2,3],dtype=torch.float32)

b=torch.tensor([5,6,7],dtype=torch.float32)

print(a+b)

tensor([ 6.,  8., 10.])


In [22]:
torch.add(a,b)

tensor([ 6.,  8., 10.])

In [23]:
c=torch.zeros(3)

**Storing in a variable**

In [24]:
torch.add(a,b,out=c)

tensor([ 6.,  8., 10.])

In [25]:
c

tensor([ 6.,  8., 10.])

In [26]:
torch.add(a,b).sum()

tensor(24.)

# Dot product and multiplication operation

**Multiplication**

In [29]:
print(a)

print(b)

a.mul(b)

tensor([1., 2., 3.])
tensor([5., 6., 7.])


tensor([ 5., 12., 21.])

In [32]:
a.dot(b)       #1.5 + 2.6 + 3.7

tensor(38.)

# Matrix multiplicaiton

In [35]:
a=torch.tensor([[4,5,6],[7,2,8]],dtype=torch.float)

b=torch.tensor([[3,2,1],[7,1,5],[1,2,3]],dtype=torch.float)

torch.matmul(a,b)

tensor([[53., 25., 47.],
        [43., 32., 41.]])

In [36]:
a@b

tensor([[53., 25., 47.],
        [43., 32., 41.]])

In [37]:
torch.mm(a,b)

tensor([[53., 25., 47.],
        [43., 32., 41.]])